### ISSUE TITLE
eip-review-bot thinks adding a markdown file in `assets` changes EIP status

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eip-review-bot#140]
Adding a new file required editor approval. Is that correct behaviour?

![image](https://user-images.githubusercontent.com/57262657/224423058-b162c901-749c-48b3-9a4b-17727f75eb99.png)

From https://github.com/ethereum/EIPs/pull/6661

**Comment by Pandapip1** [comment]
No, this is not expected behavior.

**Comment by Pandapip1** [comment]
So for some reason it seems to think that the status is being modified.

**Comment by Pandapip1** [comment]
I've identified the bug. It's mistakenly detecting a markdown file as an EIP.
