### ISSUE TITLE
Error on master when approving

### ISSUE THREAD

**Issue by lightclient** [ethereum/eip-review-bot#246]
I'm getting these errors pretty frequently, how can we avoid this?

Example: https://github.com/ethereum/EIPs/actions/runs/4701921094/jobs/8338558519

**Comment by Pandapip1** [comment]
Which PR are you trying to approve? For that particular one, it looks like there simply needs to be another editor approval.

As for the automatic pushing, that's a different question. I'll just temporarily disable it.

**Comment by lightclient** [comment]
thanks
