### ISSUE TITLE
eip bot does not assign tag/assign editor to review ERC

### ISSUE THREAD

**Issue by wongtsejian** [ethereum/eip-review-bot#353]
A PR was opened to migrate a ERC proposal form EIP repo ([PR link](https://github.com/ethereum/ERCs/pull/128)). EIP bot failed to assign an editor and reported an error. 

![image](https://github.com/ethereum/eip-review-bot/assets/109474215/96479c5e-23bb-4fb1-be4a-3273a9cbbb40)

**Comment by Pandapip1** [comment]
My guess is that it's to do with the `Gemfile.lock` file. Please undo that change and see what happens. Ideally, provide a link to the run itself, too!

**Comment by wongtsejian** [comment]
Thanks. I have undo the unintended changes to gemfile.lock.

**Comment by wongtsejian** [comment]
Although the bot still does not seem to tag editors, I noticed that SamWilson has started to review the PR. So no further issues at the moment.
