### ISSUE TITLE
eip-review-bot detects a status change with a new EIP

### ISSUE THREAD

**Issue by minkyn** [ethereum/eip-review-bot#354]
### Pull Request

https://github.com/ethereum/ERCs/pull/91

### What happened?

All other preconditions have been met for this PR, including human approval, CI checks, but the bot still won't trigger merging automatically.

![image](https://github.com/ethereum/ERCs/assets/1875412/39bacef8-dd9b-4978-b0ce-1132eac265b5)

**Comment by Pandapip1** [comment]
Okay, it appears that this is to do with creating a new EIP that contains assets. I believe I have a fix.
