### ISSUE TITLE
EIP bot does not assign tag/assign editor to review ERC

### ISSUE THREAD

**Issue by alcedo** [ethereum/eip-review-bot#379]
A PR was opened to update an ERC proposal (https://github.com/ethereum/ERCs/pull/312). EIP bot failed to assign an editor and reported an error.

<img width="915" alt="image" src="https://github.com/ethereum/eip-review-bot/assets/1174679/f1ba8541-cb69-405e-9f97-23f03b5bdf8a">

**Comment by Pandapip1** [comment]
This was apparently a GitHub bug: https://github.com/ethereum/ERCs/actions/runs/8249740227/job/22562784458

**Comment by Pandapip1** [comment]
Closing: no repro.
